/* Each new term in the Fibonacci sequence is generated by adding the previous two terms. By starting with 1 and 2, the first 10 terms will be:
1, 2, 3, 5, 8, 13, 21, 34, 55, 89, ...
By considering the terms in the Fibonacci sequence whose values do not exceed four million, find the sum of the even-valued terms.
*/

#include <iostream>
using namespace std;

const int MAX = 4000000;

int main() {
	int lastTerm = 0;
	int currentTerm = 0;
	int sum = 0;

	for (int i = 1; i < MAX; i) {
		if ((i % 2) == 0) {
			sum += i;
		}
		lastTerm = currentTerm;
		currentTerm = i;
		i += lastTerm;
	}

	cout << sum << endl;
}